[project]
name = "scalable-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "modal>=1.2.4",
    "pandas>=2.3.3",
    "torch==2.2.2",
    "unsloth>=2024.8",
]
